### ISSUE TITLE
Make the website responsive

### ISSUE THREAD

**Issue by ArchismanKarmakar** [ArchismanKarmakar/business-website-codepeak2021#1]

**Comment by Code-Aditya-14** [comment]
I would like to work on this issue.

**Comment by ArchismanKarmakar** [comment]
Yes go on

**Comment by ArchismanKarmakar** [comment]
> I would like to work on this issue.

before working please remove all the CSS in the HTML file and add them in separate style.css and then work

**Comment by ArchismanKarmakar** [comment]
> I would like to work on this issue.

you can use bootstrap, I am merging issue #2 with this.

**Comment by ArchismanKarmakar** [comment]
> > I would like to work on this issue.
> 
> you can use bootstrap, I am merging issue #2 with this. You will get 10 points for this.
refer to this image add a banner like this in index and add carousel to it

![index1](https://user-images.githubusercontent.com/92569441/145055379-b6fd81a4-a53a-4eca-b2b6-9e797b6d35d3.png)

**Comment by ArchismanKarmakar** [comment]
> I would like to work on this issue.

nice work #28
