### ISSUE TITLE
Add a page for Weddings, meet-ups at ITC hotel banquets.

### ISSUE THREAD

**Issue by ArchismanKarmakar** [ArchismanKarmakar/business-website-codepeak2021#10]

**Comment by Sanath91009** [comment]
Claim

**Comment by Sanath91009** [comment]
I have made PR to my assigned issue . Now can you assign this to me ?

**Comment by ArchismanKarmakar** [comment]
> I have made PR to my assigned issue . Now can you assign this to me ?

yes go ahead, note: create new html page with bootstrap or react, any one of ur choice

**Comment by ArchismanKarmakar** [comment]
> I have made PR to my assigned issue . Now can you assign this to me ?

are you working?

**Comment by re4lvanshsingh** [comment]
can i take this issue?

**Comment by ArchismanKarmakar** [comment]
> can i take this issue?

go ahead use bootstrap, for content refer to ITC hotels website & SITEMAP is below:

![Sitemap](https://user-images.githubusercontent.com/92569441/145706517-dd4d8722-cbc5-4850-8535-ad339165ece9.png)
