### ISSUE TITLE
Add a user feedback form & add backend.

### ISSUE THREAD

**Issue by ArchismanKarmakar** [ArchismanKarmakar/business-website-codepeak2021#12]

**Comment by Sanath91009** [comment]
For this can we do front end part in html and css and for backend in php ?

**Comment by ArchismanKarmakar** [comment]
> For this can we do front end part in html and css and for backend in php ?

no PHP, but you can use mongo or firebase with JS which is quite easier than PHP

**Comment by ArchismanKarmakar** [comment]
> For this can we do front end part in html and css and for backend in php ?

also same project with a lots of different backend things will be hectic ig.

**Comment by shmiitg** [comment]
do we need the frontend part also, if we need only backend then I will take this issue

**Comment by ArchismanKarmakar** [comment]
> do we need the frontend part also, if we need only backend then I will take this issue

yes you need to create a page containing the user feedback form with React or bootstrap and add a back-end to it

**Comment by shmiitg** [comment]
actually i was thinking that i will just create a form (without any css) and add required backend to it, then later the form styling can be done in some issue

**Comment by ArchismanKarmakar** [comment]
> ome issue

you can do that, if you do it I'll put another issue for it. you can go with just a boiler plate form and add backend, should i assign you now?

**Comment by shmiitg** [comment]
yaah I will take this

**Comment by ArchismanKarmakar** [comment]
> yaah I will take this

go ahead
