### ISSUE TITLE
Make the club page mention features, use bootstrap

### ISSUE THREAD

**Issue by ArchismanKarmakar** [ArchismanKarmakar/business-website-codepeak2021#13]

**Comment by shmiitg** [comment]
Do we need to fill any data in mongodb database or use hotels.json file only?

**Comment by ArchismanKarmakar** [comment]
> Do we need to fill any data in mongodb database or use hotels.json file only?

You can fill the data in hotels.json like

Spa: yes
Features: ...
Programmes offered:...

**Comment by ArchismanKarmakar** [comment]
> > Do we need to fill any data in mongodb database or use hotels.json file only?
> 
> You can fill the data in hotels.json like
> 
> Spa: yes
> Features: ...
> Programmes offered:...

Should I assign you ?

**Comment by shmiitg** [comment]
> > > Do we need to fill any data in mongodb database or use hotels.json file only?
> > 
> > 
> > You can fill the data in hotels.json like
> > Spa: yes
> > Features: ...
> > Programmes offered:...
> 
> Should I assign you ?

I just asked out of curiosity. Actually, I am not very good in frontend part, so I usually take backend work only

**Comment by ArchismanKarmakar** [comment]
> > > > Do we need to fill any data in mongodb database or use hotels.json file only?
> > > 
> > > 
> > > You can fill the data in hotels.json like
> > > Spa: yes
> > > Features: ...
> > > Programmes offered:...
> > 
> > Should I assign you ?
> 
> I just asked out of curiosity. Actually, I am not very good in frontend part, so I usually take backend work only

You have to use bootstrap here, haven't you checked the sitemap??

**Comment by ArchismanKarmakar** [comment]
> > > > Do we need to fill any data in mongodb database or use hotels.json file only?
> > > 
> > > 
> > > You can fill the data in hotels.json like
> > > Spa: yes
> > > Features: ...
> > > Programmes offered:...
> > 
> > Should I assign you ?
> 
> I just asked out of curiosity. Actually, I am not very good in frontend part, so I usually take backend work only

The react app is for inner part...

**Comment by re4lvanshsingh** [comment]
@ArchismanKarmakar can i solve this issue?

**Comment by ArchismanKarmakar** [comment]
> @ArchismanKarmakar can i solve this issue?

go ahead
