### ISSUE TITLE
1 Credit for newbies: Split out the CSS into seperate files outside the main HTML in assets/css/

### ISSUE THREAD

**Issue by ArchismanKarmakar** [ArchismanKarmakar/business-website-codepeak2021#15]

**Comment by Sanath91009** [comment]
Claim

**Comment by ArchismanKarmakar** [comment]
> Claim

go ahead

**Comment by ArchismanKarmakar** [comment]
> Claim

fix the background. the background had the GIF but its not working now. fix it. except that rest are fine

**Comment by Sanath91009** [comment]
but its working fine for me ...

**Comment by ArchismanKarmakar** [comment]
> but its working fine for me ...

you have used:   `background-image: url(img/img4.gif);`
but the CSS file is unable to get img as img is in root folder so change it to  `background-image: url(../../img/img4.gif);`

**Comment by ArchismanKarmakar** [comment]
#17 closed
