### ISSUE TITLE
Install the required packages with npm & upload the package.json file

### ISSUE THREAD

**Issue by ArchismanKarmakar** [ArchismanKarmakar/business-website-codepeak2021#16]

**Comment by Sanath91009** [comment]
Claim

**Comment by shmiitg** [comment]
Can I work on this. I have some packages in mind that will be required in the later stage of the project.

**Comment by ArchismanKarmakar** [comment]
> Can I work on this. I have some packages in mind that will be required in the later stage of the project.

go ahead sir
