### ISSUE TITLE
Typos in README

### ISSUE THREAD

**Issue by pushkar2112** [ArchismanKarmakar/business-website-codepeak2021#20]
There are some typos in the README.md file

**Comment by pushkar2112** [comment]
Pls add necessary labels.

**Comment by pushkar2112** [comment]
I would like to work on this.

**Comment by ArchismanKarmakar** [comment]
> I would like to work on this.

continue after you finish previous one and make a PR

**Comment by ArchismanKarmakar** [comment]
> > I would like to work on this.
> 
> continue after you finish previous one and make a PR

go ahead

**Comment by ArchismanKarmakar** [comment]
> I would like to work on this.

thanks man for it #25
