### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by pushkar2112** [ArchismanKarmakar/business-website-codepeak2021#21]
# Description
This project does not have an issue template. Create an issue template. The template would look something like this -

# Description
# Relevant files
# Screenshot
# References

**Comment by pushkar2112** [comment]
Pls add necessary labels.

**Comment by pushkar2112** [comment]
I would like to work on this.

**Comment by ArchismanKarmakar** [comment]
> I would like to work on this.

go ahead
