### ISSUE TITLE
Add Pull Request template

### ISSUE THREAD

**Issue by pushkar2112** [ArchismanKarmakar/business-website-codepeak2021#22]
The project does not have a PR template.
Should look something like -

## Issue
Fixes #(Mention the issue ID here)

## Checklist
- [ ] The app builds properly
- [ ] Code is commented in difficult to understand areas
- [ ] Code is formatted well

**Comment by pushkar2112** [comment]
Pls add necessary labels.

**Comment by pushkar2112** [comment]
I would like to work on this.

**Comment by ArchismanKarmakar** [comment]
#24
