### ISSUE TITLE
Frontend development for login and signup page; use React

### ISSUE THREAD

**Issue by shmiitg** [ArchismanKarmakar/business-website-codepeak2021#29]
# Description
The frontend for login and signup is very minimal. It would be good if its frontend is improved

After signup / login the user to be redirected to the react page for hotels & resorts and react page for confirm booking

**Comment by Collatz-Conjecture315** [comment]
![new-login-page-pic](https://user-images.githubusercontent.com/81220220/145359293-33c61fbc-a18d-46cd-976e-87d83d74e12e.JPG)
I havent used react,but it now looks like this.

**Comment by ArchismanKarmakar** [comment]
> ![new-login-page-pic](https://user-images.githubusercontent.com/81220220/145359293-33c61fbc-a18d-46cd-976e-87d83d74e12e.JPG) I havent used react,but it now looks like this.

its basic html wrt it its good but use react

**Comment by ArchismanKarmakar** [comment]
> ![new-login-page-pic](https://user-images.githubusercontent.com/81220220/145359293-33c61fbc-a18d-46cd-976e-87d83d74e12e.JPG) I havent used react,but it now looks like this.

if you know react & willing to do this i can assign you

**Comment by Jhanvi528** [comment]
I can do this task. please assign this task to me.

**Comment by ArchismanKarmakar** [comment]
> I can do this task. please assign this task to me.

go ahead ### use react

**Comment by ArchismanKarmakar** [comment]
> I can do this task. please assign this task to me.

also check the sitemap.png before working

**Comment by shmiitg** [comment]
can I get this issue if @Jhanvi528 is not working on it?

**Comment by rt-001** [comment]
If no one is working on this, I would like to do this.

**Comment by ArchismanKarmakar** [comment]
> If no one is working on this, I would like to do this.

go ahead, looks like Jhanvi528 is not working

**Comment by rt-001** [comment]
@ArchismanKarmakar  
Is this ok ?
![image](https://user-images.githubusercontent.com/76102333/146182601-6109dd89-d925-451a-9c2b-74920404fab7.png)

**Comment by ArchismanKarmakar** [comment]
> @ArchismanKarmakar  
> Is this ok ?
> ![image](https://user-images.githubusercontent.com/76102333/146182601-6109dd89-d925-451a-9c2b-74920404fab7.png)
> 
> 

Yeah this looks great 👍 can you add a animated background?? Doing it you will get some 10 points + some bonus (max5)

**Comment by rt-001** [comment]
Yes, I can

**Comment by ArchismanKarmakar** [comment]
> Yes, I can 
> 

How is it going?? Have you completed the task??

**Comment by shmiitg** [comment]
can i take over this issue?

**Comment by ArchismanKarmakar** [comment]
> can i take over this issue?

go ahead bhaiya,... aap to top kar gye congratz

**Comment by ShivaRapolu01** [comment]
Can I also try on this parallelly?

**Comment by ArchismanKarmakar** [comment]
> Can I also try on this parallelly?

yes

**Comment by ArchismanKarmakar** [comment]
i will take the best one

**Comment by ArchismanKarmakar** [comment]
@shmiitg please fix the bug, clicking the login/signup button not launching the react app
