### ISSUE TITLE
Add Express backend to the website.

### ISSUE THREAD

**Issue by ArchismanKarmakar** [ArchismanKarmakar/business-website-codepeak2021#3]

**Comment by shmiitg** [comment]
I would like to work on this. Please assign me

**Comment by ArchismanKarmakar** [comment]
> I would like to work on this. Please assign me

go ahead.

one thing please note: separate the CSS inside HTML and add them in different CSS files in the names of their respective HTML.

like for index.html its index.css for contacts.html its contacts.css

**Comment by ArchismanKarmakar** [comment]
> I would like to work on this. Please assign me

just wait for some time I'll assign you, I am waiting for an update. once done I'll assign you.

**Comment by shmiitg** [comment]
ok

**Comment by ArchismanKarmakar** [comment]
> ok

You are ready to go

**Comment by shmiitg** [comment]
ok

**Comment by shmiitg** [comment]
do i need to render any pages?
I just added the server to the backend
![Screenshot (271)](https://user-images.githubusercontent.com/70333141/145047450-23ba83f1-aba4-4717-a791-67969da6fff7.png)

**Comment by ArchismanKarmakar** [comment]
> do i need to render any pages? I just added the server to the backend ![Screenshot (271)](https://user-images.githubusercontent.com/70333141/145047450-23ba83f1-aba4-4717-a791-67969da6fff7.png)

if this was to display only hello i would have given it label for learners only. Please don't mind anything for this. but you say what do you think??

**Comment by shmiitg** [comment]
ok i got it ! Sorry for inconvenience

**Comment by ArchismanKarmakar** [comment]
> ok i got it ! Sorry for inconvenience

its okay no problem

**Comment by ArchismanKarmakar** [comment]
> ok i got it ! Sorry for inconvenience

great work man
#19

**Comment by shmiitg** [comment]
thanks
