### ISSUE TITLE
Add Encryption preferably AES256 / RSA use private, public keys for user credentials.

### ISSUE THREAD

**Issue by ArchismanKarmakar** [ArchismanKarmakar/business-website-codepeak2021#38]
# Description
Use AES256 or higher algo, use SHA256 / RSA hashing algo, use private, public key pairs, AES CBC 256

**Comment by shmiitg** [comment]
You can assign me this issue. I will use aes256 for this but i think aes 256 don't have private and public keys, correct me if I am wrong

**Comment by ArchismanKarmakar** [comment]
> You can assign me this issue. I will use aes256 for this but i think aes 256 don't have private and public keys, correct me if I am wrong

oops sorry. i forgot to mention RSA

**Comment by ArchismanKarmakar** [comment]
> You can assign me this issue. I will use aes256 for this but i think aes 256 don't have private and public keys, correct me if I am wrong

by the way are you a 3rd yr student??

**Comment by ArchismanKarmakar** [comment]
> You can assign me this issue. I will use aes256 for this but i think aes 256 don't have private and public keys, correct me if I am wrong

i also worked in my pwd manager, so i know AES256 CBC, GCM

**Comment by shmiitg** [comment]
> > You can assign me this issue. I will use aes256 for this but i think aes 256 don't have private and public keys, correct me if I am wrong
> 
> by the way are you a 3rd yr student??

yes

**Comment by shmiitg** [comment]
> > You can assign me this issue. I will use aes256 for this but i think aes 256 don't have private and public keys, correct me if I am wrong
> 
> i also worked in my pwd manager, so i know AES256 CBC, GCM

cool . I will use CBC for this
