### ISSUE TITLE
ReadMe update for backend 

### ISSUE THREAD

**Issue by shmiitg** [ArchismanKarmakar/business-website-codepeak2021#40]
# Description
The backend folder readme is empty. It should have things on how to start the server, how to connect to mongodb, what things to include in .env file and all other required things.

**Comment by rt-001** [comment]
I would like to take this issue.

**Comment by ArchismanKarmakar** [comment]
> I would like to take this issue.

Go ahead

**Comment by varunmishrak99** [comment]
I would like to work on this issue . Please assign me this issue

**Comment by ArchismanKarmakar** [comment]
> I would like to work on this issue . Please assign me this issue

Go ahead

**Comment by shmiitg** [comment]
If no one is working on this, I would like to do this.

**Comment by ArchismanKarmakar** [comment]
> If no one is working on this, I would like to do this.

just wait one more day and you can work with this.

**Comment by shmiitg** [comment]
> > If no one is working on this, I would like to do this.
> 
> just wait one more day and you can work with this.

ok sure

**Comment by varunmishrak99** [comment]
sorry please assign this work to someone else

**Comment by ArchismanKarmakar** [comment]
> > > If no one is working on this, I would like to do this.
> > 
> > 
> > just wait one more day and you can work with this.
> 
> ok sure

go ahead now
