### ISSUE TITLE
Issue with serving static files with assets & CSS & redirecting to new pages.

### ISSUE THREAD

**Issue by ArchismanKarmakar** [ArchismanKarmakar/business-website-codepeak2021#41]
### Please check the video

https://user-images.githubusercontent.com/92569441/145849601-6e571d7f-1a31-4e33-b55e-b485d94ff530.mp4

**Comment by shmiitg** [comment]
I will take this. I think all href links in the html files have to updated

**Comment by re4lvanshsingh** [comment]
could i solve this issue

**Comment by ArchismanKarmakar** [comment]
first decide who is going to solve this issue

**Comment by ArchismanKarmakar** [comment]
according to rules, shubham bhaiya will get this issue, sorry vansh.

**Comment by ArchismanKarmakar** [comment]
> I will take this. I think all href links in the html files have to updated

just add `app.use(express.static(path.join(__dirname,"../frontend/")));`
everything will be fixed in one.

**Comment by shmiitg** [comment]
Yaah done.
