### ISSUE TITLE
Navigation Toggle buttton not visible but it's there . Colour needs to be changed.

### ISSUE THREAD

**Issue by gauravkumar5089** [ArchismanKarmakar/business-website-codepeak2021#44]
# Description
Navigation Toggle buttton is not visible but it's there . It's colour has to be changed.

# Relevant files
Mention the files that are relevant to this issue

# Screenshot
Please attach screenshots for the same, if applicable
![image](https://user-images.githubusercontent.com/72368836/146038577-73c7eebf-231f-4fae-98ad-fea6d83e2b1f.png)

# References
Add file reference link here

**Comment by gauravkumar5089** [comment]
I am working on it.

**Comment by ArchismanKarmakar** [comment]
#42 #43
