### ISSUE TITLE
Add a Firebase/MongoDB user encrypted account & login system.

### ISSUE THREAD

**Issue by ArchismanKarmakar** [ArchismanKarmakar/business-website-codepeak2021#5]

**Comment by shmiitg** [comment]
I would like to work on this issue. I will use mongodb and jwt for this purpose

**Comment by ArchismanKarmakar** [comment]
> I would like to work on this issue. I will use mongodb and jwt for this purpose

great work sir, i will check this and approve the PR, please wait till then

**Comment by shmiitg** [comment]
I forgot to mention this yesterday. Actually i got only 7 points for this issue and in the scoring criteria its mentioned 10-12 points for hard issue.

**Comment by ArchismanKarmakar** [comment]
> I forgot to mention this yesterday. Actually i got only 7 points for this issue and in the scoring criteria its mentioned 10-12 points for hard issue.

let me check, if yes i will correct it.

**Comment by ArchismanKarmakar** [comment]
> I forgot to mention this yesterday. Actually i got only 7 points for this issue and in the scoring criteria its mentioned 10-12 points for hard issue.

check now

**Comment by shmiitg** [comment]
Its fine now. Thanks

**Comment by ArchismanKarmakar** [comment]
> Its fine now. Thanks

you are just behind me, 4 points difference 😃

**Comment by shmiitg** [comment]
yaah, lol
