### ISSUE TITLE
BUG: Clicking Login/Signup should immediately switch to the login/signup page of the React App; as per sitemap.

### ISSUE THREAD

**Issue by ArchismanKarmakar** [ArchismanKarmakar/business-website-codepeak2021#52]
###  Also delete the login/signup html as the react app is there**

![SITEAMP](https://user-images.githubusercontent.com/92569441/145706517-dd4d8722-cbc5-4850-8535-ad339165ece9.png)

**Comment by ShivaRapolu01** [comment]
Can I work on this issue?

**Comment by ArchismanKarmakar** [comment]
> Can I work on this issue?

go ahead.

**Comment by ArchismanKarmakar** [comment]
> Can I work on this issue?

did you understand what i meant??

**Comment by ShivaRapolu01** [comment]
Yeah
1) redirecting to login and signup page made with react
2) deleting login/signup html

**Comment by ArchismanKarmakar** [comment]
> Yeah
> 
> 1. redirecting to login and signup page made with react
> 2. deleting login/signup html

yeah go ahead

**Comment by ArchismanKarmakar** [comment]
> Yeah
> 
> 1. redirecting to login and signup page made with react
> 2. deleting login/signup html

how is it going on @ShivaRapolu01 ? are you working?

**Comment by ShivaRapolu01** [comment]
Working on it will try to submit by tommorow

**Comment by ArchismanKarmakar** [comment]
> Working on it will try to submit by tommorow

yeah yeah go on no hurry, i just wanted to know if you are still working; i am doing as per instructions from coordinator, thanks

**Comment by ShivaRapolu01** [comment]
Status : converted index.html into Home.js(into react) but I have fallen into errors ,fixing them
