### ISSUE TITLE
The Navbar is being displayed twice 

### ISSUE THREAD

**Issue by ShivaRapolu01** [ArchismanKarmakar/business-website-codepeak2021#53]
# Description
The Navbar is being displayed twice  

# Relevant files
index.html

# Screenshot
![image](https://user-images.githubusercontent.com/79957651/146683334-cd4a3a46-c878-481d-8125-4526a7986029.png)

**Comment by ShivaRapolu01** [comment]
I am willing to work on this

**Comment by ArchismanKarmakar** [comment]
> I am willing to work on this

sorry bro.... already someone is working on it, he showed me, so you can try some other issue
