### ISSUE TITLE
remove Horizontal scroll in weddings.html

### ISSUE THREAD

**Issue by ShivaRapolu01** [ArchismanKarmakar/business-website-codepeak2021#57]
# Description
The horizontal scrollbar hinders the user's experience, There is a additional gap created between the content of the page and vertical scrollbar due to this ,  The Horizontal scrollbar must be removed 

# Relevant files
weddings.html

# Screenshot
![image](https://user-images.githubusercontent.com/79957651/146780207-4ff09efc-1c77-4d95-b60b-57cfbdde7de1.png)

# References
Add file reference link here

**Comment by ShivaRapolu01** [comment]
I have a quick fix for this, can I work on this?

**Comment by ArchismanKarmakar** [comment]
> I have a quick fix for this, can I work on this?
@re4lvanshsingh already informed me this thing, he is working on it
