### ISSUE TITLE
Use React to add User profile pages & add backend.

### ISSUE THREAD

**Issue by ArchismanKarmakar** [ArchismanKarmakar/business-website-codepeak2021#60]
# Description
Use React to add User profile pages. profile, edit, confirmation pages

# References
sitemap1.png

![MAP](https://user-images.githubusercontent.com/92569441/145590394-73a5533a-b4ff-4d18-9097-92d347030174.png)

**Comment by sanathk12** [comment]
Claim

**Comment by ArchismanKarmakar** [comment]
> Claim

go ahead

**Comment by shmiitg** [comment]
Can i take over this issue if @sanathk12 is not working?

**Comment by ArchismanKarmakar** [comment]
> Can i take over this issue if @sanathk12 is not working?

yes both of you can work and first come first serve

**Comment by shmiitg** [comment]
@ArchismanKarmakar I think you gave me 15 points instead of 20, please verify

**Comment by ArchismanKarmakar** [comment]
> @ArchismanKarmakar I think you gave me 15 points instead of 20, please verify

yeah sorry bhaiya. I have updated it. Sorry bhaiya
