### ISSUE TITLE
Add backend to link payment gateway with bookings page

### ISSUE THREAD

**Issue by ArchismanKarmakar** [ArchismanKarmakar/business-website-codepeak2021#61]
# Description
Add backend to link payment gateway with bookings page. For Payment gateway use temporary addresses. Do not put real addresses. Use any random id just to test if it is working.

# Caution!!: Before working please check the T&C:

- [ ] I agree that the mentor of this project will not be responsible for any kind of problems, if I provided my personal payment information or credentials in public. This issues are to be worked out only for testing & personal skill development as this is part of the CODEPEAK program under Indian Institute of Technology.

# Relevant files

# References
![map1](https://user-images.githubusercontent.com/92569441/145706517-dd4d8722-cbc5-4850-8535-ad339165ece9.png)

**Comment by shmiitg** [comment]
I am working on it. You can assign me this issue
