### ISSUE TITLE
[Frontend] Fix all the static HTML pages make the pages look good

### ISSUE THREAD

**Issue by ArchismanKarmakar** [ArchismanKarmakar/business-website-codepeak2021#66]
# Relevant files
All static HTML files inside Frontend folder

# References
![Sitemap](https://user-images.githubusercontent.com/92569441/145706517-dd4d8722-cbc5-4850-8535-ad339165ece9.png)

**Comment by re4lvanshsingh** [comment]
Could i work on this issue? @ArchismanKarmakar

**Comment by ArchismanKarmakar** [comment]
> Could i work on this issue? @ArchismanKarmakar 

Go ahead
