### ISSUE TITLE
Add a welcome banner in index.html (refer to PPT)

### ISSUE THREAD

**Issue by ArchismanKarmakar** [ArchismanKarmakar/business-website-codepeak2021#7]
Add a welcome banner in index.html (refer to [PPT](https://github.com/ArchismanKarmakar/ITC-hotels-codepeak2021/blob/main/project-ppt.pptx))

**Comment by Sanath91009** [comment]
Claim

**Comment by ArchismanKarmakar** [comment]
> Claim

one issue at a time

**Comment by Sanath91009** [comment]
Now can you assign it to me ? @ArchismanKarmakar

**Comment by ArchismanKarmakar** [comment]
> Claim

now you can continue, please check the ppt & ITC hotels website for a good banner. It need not to look exactly same but you can take it as a idea. you can use bootstrap & react also.

**Comment by ArchismanKarmakar** [comment]
follow this image to make a banner

![index1](https://user-images.githubusercontent.com/92569441/145054720-0c170715-b84c-47b2-8c27-57efb05466b4.png)
