### ISSUE TITLE
Navbar component in react app

### ISSUE THREAD

**Issue by shmiitg** [ArchismanKarmakar/business-website-codepeak2021#71]
# Description
React files to have a navbar component that will be consistent in all react pages. Moreover the login and signup button should change to a dropdown menu that will contain links for user dashboard and logout when user is logged in

**Comment by Sanath91009** [comment]
claim

**Comment by Sanath91009** [comment]
What is the api to get user details ?

**Comment by shmiitg** [comment]
> What is the api to get user details ?

i guess it was /user/profile

**Comment by Sanath91009** [comment]
http://localhost:5000/api/user/profile ?

**Comment by ArchismanKarmakar** [comment]
> claim



> claim

one issue at a time. please.
