### ISSUE TITLE
Login and register form not looking great

### ISSUE THREAD

**Issue by shmiitg** [ArchismanKarmakar/business-website-codepeak2021#79]
# Description
The font size got reduced in some previous commit and the login and register form is not looking great now. It may also be possible because of using bootstrap. Also due to navbar there is a vertical scroll bar which is not looking great

![Screenshot (372)](https://user-images.githubusercontent.com/70333141/148267349-5755cfa4-d0d4-4d3f-a360-fca803d7955b.png)

**Comment by shmiitg** [comment]
I am fixing these

**Comment by ArchismanKarmakar** [comment]
okay bhaiya
