### ISSUE TITLE
Use MongoDB to add all hotels & resorts in the website present across India. 

### ISSUE THREAD

**Issue by ArchismanKarmakar** [ArchismanKarmakar/business-website-codepeak2021#8]
hotels.html for displaying all hotels & resorts

**Comment by shmiitg** [comment]
do we need to manually add data to the database ? In the project local database is connected, so it wont be available everywhere. And for displaying the data from database we need to use template engines like ejs or hbs .

**Comment by ArchismanKarmakar** [comment]
> do we need to manually add data to the database ? In the project local database is connected, so it wont be available everywhere. And for displaying the data from database we need to use template engines like ejs or hbs .

Yes check the ITC hotels website and fill the database with all hotels & resorts with features and then use react to display them in the hotels page

**Comment by shmiitg** [comment]
If we use a local database, then it won't be available to everyone. We should use monogdb atlas for this right?

**Comment by ArchismanKarmakar** [comment]
> 

yeah I guess, i don't have it so never used it, i always use mongodb compass so i guess you are right

**Comment by shmiitg** [comment]
can we use template engines like ejs for this, if we use react then we have to use two different ports(one for express and other for react) and we have to change the folder structure and change all the get routes in express and create new routes to run in react, this process will be very hectic and will involve a lot of changes in the entire code. So i guess using ejs or hbs will be better.

**Comment by ArchismanKarmakar** [comment]
> can we use template engines like ejs for this, if we use react then we have to use two different ports(one for express and other for react) and we have to change the folder structure and change all the get routes in express and create new routes to run in react, this process will be very hectic and will involve a lot of changes in the entire code. So i guess using ejs or hbs will be better.

Yes u can should i assign u

**Comment by shmiitg** [comment]
Can you split this issue into two different parts, one for creating the filling the database and other for using frontend to fetch and display the data. I am not sure about what data to store in mongodb for this, so if someone has put the data, then I can use it.

**Comment by shmiitg** [comment]
![Screenshot (276)](https://user-images.githubusercontent.com/70333141/145463188-815627a3-6307-4e1f-be2e-ec1c49b2610e.png)
Do we need to add all these hotel names and display it like this? 
![Screenshot (277)](https://user-images.githubusercontent.com/70333141/145463336-fb156ade-f299-4a9e-acbc-f88595587d68.png)
If we have to do this, then you can assign me

**Comment by ArchismanKarmakar** [comment]
> ![Screenshot (276)](https://user-images.githubusercontent.com/70333141/145463188-815627a3-6307-4e1f-be2e-ec1c49b2610e.png)
> Do we need to add all these hotel names and display it like this? 
> ![Screenshot (277)](https://user-images.githubusercontent.com/70333141/145463336-fb156ade-f299-4a9e-acbc-f88595587d68.png)
> If we have to do this, then you can assign me
> 

Yes if you are using bootstrap/tailwind then use card system or something better. But add all the hotels & resorts

**Comment by ArchismanKarmakar** [comment]
> ![Screenshot (276)](https://user-images.githubusercontent.com/70333141/145463188-815627a3-6307-4e1f-be2e-ec1c49b2610e.png)
> Do we need to add all these hotel names and display it like this? 
> ![Screenshot (277)](https://user-images.githubusercontent.com/70333141/145463336-fb156ade-f299-4a9e-acbc-f88595587d68.png)
> If we have to do this, then you can assign me
> 

It was my school project, previous i created with css as js but school won't understand it so removed everything.

**Comment by shmiitg** [comment]
I have put everything in mongodb (total 57 documents are there and it took a lot of time i adding all those manually). I have not created any cards but not rendered the names as it was there in the hotels.html file, but mongodb contains all the things as there in itc website.
![Screenshot (278)](https://user-images.githubusercontent.com/70333141/145516453-24c303e0-c6b3-4cc8-be86-76c28319706f.png)
For creating cards as you said, could you please assign someone else.

**Comment by ArchismanKarmakar** [comment]
> reating cards as you said, could you please assign someone else

great work, okay i will put a new issue then
